### ISSUE TITLE
get error when "make docker"

### ISSUE THREAD

**Issue by Lewis-Kang** [opencomputeproject/OpenNetworkLinux#31] opened 2016-02-02 03:59 UTC
....
Multistrap system installed successfully in /home2/kang/OCP/OpenNetworkLinux/builds/powerpc/rootfs/builds/rootfs-powerpc.d/.

DEBUG:onlrfs:Executing:sudo mount -t devtmpfs dev rootfs-powerpc.d/dev
DEBUG:onlrfs:Executing:sudo mount -t proc proc rootfs-powerpc.d/proc
DEBUG:onlrfs:Executing:sudo cp /usr/bin/qemu-ppc-static rootfs-powerpc.d/usr/bin
INFO:onlrfs:dpkg-configure filesystem...
DEBUG:onlrfs:Executing:sudo chroot rootfs-powerpc.d /tmp/configure.sh
chroot: failed to run command `/tmp/configure.sh': Exec format error
DEBUG:onlrfs:Executing:sudo umount -l rootfs-powerpc.d/dev rootfs-powerpc.d/proc
ERROR:onlrfs:Post Configuration failed.
make[2]: *** [RFS] Error 1
make[2]: Leaving directory `/home2/kang/OCP/OpenNetworkLinux/builds/powerpc/rootfs/builds'
ERROR:onlpm:'Build failed.'
make[1]: *** [pkgall] Error 1
make[1]: Leaving directory `/home2/kang/OCP/OpenNetworkLinux/builds/powerpc/rootfs'
make: *** [ppc] Error 2

**Comment by sonoble** [comment] 2016-02-02 04:08
Hi Lewis, 

@jnealtowns and I are looking in to this issue, I have been seeing it on my non bsn build machines. It has something to do with qemu/binfmt.

**Comment by capveg** [comment] 2016-02-02 04:11
Hi Lewis,

Can you confirm that you have binfmt-support installed on your building
machine?

robs@ubudev:~$ dpkg -l | grep binfmt
ii  binfmt-support                         2.1.4-1
        amd64        Support for extra binary formats

- Rob
.

**Comment by Lewis-Kang** [comment] 2016-02-02 04:14
Hi Rob, 

Yes. It's installed.

root@CicadaBuildServer:/home2/kang/OCP/OpenNetworkLinux# dpkg -l | grep binfmt
ii  binfmt-support                        2.1.5-1                              amd64        Support for extra binary formats

**Comment by capveg** [comment] 2016-02-02 04:42
@Steve:

So, I think I'm starting to figure out the problem.  I've replicated this
on my local VM setup and it seem like the problem is how the
tmp/configure.sh script is created
(~/builds/powerpc/rootfs/builds/rootfs-powerpc.d/tmp/configure.sh).
Critically, the file has a '\n' for the first line of the file so the
system can't decide how to run the file.

Now - I'm going to try to figure out why this file is correctly generated
for us on our build servers and incorrectly for other folks.

@Lewis: can you confirm that this file is similarly corrupted for you?

- Rob
.

**Comment by capveg** [comment] 2016-02-02 05:00
So, I think this is the problem:

robs@ubudev:~/work.onl/OpenNetworkLinux$ git diff
diff --git a/packages/base/any/initrds/buildroot/builds/buildroot-mirror
b/packages/base/any/initrds/buildroot/builds/buildroot-mirror
--- a/packages/base/any/initrds/buildroot/builds/buildroot-mirror
+++ b/packages/base/any/initrds/buildroot/builds/buildroot-mirror
@@ -1 +1 @@
-Subproject commit 5e1a5c1ef7bac890845920809147ee2070dc96ea
+Subproject commit 5e1a5c1ef7bac890845920809147ee2070dc96ea-dirty
diff --git a/tools/onlrfs.py b/tools/onlrfs.py
index fb03c69..2ad30e4 100755
--- a/tools/onlrfs.py
+++ b/tools/onlrfs.py
@@ -266,8 +266,8 @@ class OnlRfsBuilder(object):
         script = os.path.join(dir_, "tmp/configure.sh")
         with open(script, "w") as f:
             os.chmod(script, 0700)
-            f.write("""
-#!/bin/bash -ex
+            f.write(
+"""#!/bin/bash -ex

@Lewis: I'm going to try to rebuild using this patch but if you want to
take a swing in parallel, please feel free.

- Rob
.

**Comment by capveg** [comment] 2016-02-02 06:04
So, I'm a moron - apparently Unix is smarter than I am and has no trouble
executing shell scripts that start with a \n.

That said, I believe I've found the problem:  Before the binfmt stuff will
work, we need to run inside the docker image:

`sudo mount binfmt_misc -t binfmt_misc /proc/sys/fs/binfmt_misc`
`sudo /etc/init.d/binfmt-support start`

When I do these things inside my docker image, then I can successfully
build the image.  Let me sync up with Jeff and Steve tomorrow to make sure
this is a proper fix.

- Rob
.

**Comment by capveg** [comment] 2016-02-08 22:51
Code fix posted here: https://github.com/opencomputeproject/OpenNetworkLinux/pull/33

Reviewing now.

**Comment by capveg** [comment] 2016-02-08 22:57
Merged -- please reopen if you see this issue again and thanks.

**Closed by capveg** 2016-02-08 22:57 UTC

**Comment by Dodain** [comment] 2016-02-10 21:21
I tried to do everything ,even delete the OpenNetworkLinux and start from zero but still the problem persists .
@Lewis-Kang  Are you still having this issue or is it solved ?

**Comment by sonoble** [comment] 2016-02-10 22:16
Hi Moiz,

Can you run the commands directly and see if everything works?

docker/tools/onlbuilder
source setup.env
apt-cacher-ng
sudo mount binfmt_misc -t binfmt_misc /proc/sys/fs/binfmt_misc
sudo /etc/init.d/binfmt-support start
make

**Comment by Dodain** [comment] 2016-02-12 13:55
Well everything is working except when i give the make command it gives me the following error.

make[2]: Entering directory '/home/moizimtiaz/OpenNetworkLinux/packages/base/amd64/onlp/builds'
make[3]: *** No rule to make target '/usr/include/linux/i2c-devices.h', needed by 'BUILD/jessie/x86_64-linux-gnu/obj//home/moizimtiaz/OpenNetworkLinux/packages/base/any/onlp/src/onlplib//module/src//i2c.o'.  Stop.
/home/moizimtiaz/OpenNetworkLinux/make/subdirs.mk:15: recipe for target 'all' failed
make[2]: *** [all] Error 1
make[2]: Leaving directory '/home/moizimtiaz/OpenNetworkLinux/packages/base/amd64/onlp/builds'
ERROR:onlpm:'Build failed.'
/tmp/tmpznr6XP/tmp/tmpZ_Oyes/tmp/tmpghl2FR/home/moizimtiaz/OpenNetworkLinux/make/pkg.mk:21: recipe for target 'pkgall' failed
make[1]: *** [pkgall] Error 1
make[1]: Leaving directory '/home/moizimtiaz/OpenNetworkLinux/packages/base'
Makefile:19: recipe for target 'amd64' failed
make: *** [amd64] Error 2

- Moiz

**Comment by capveg** [comment] 2016-02-12 18:00
Are you building from the docker environment?  If so, that file should
exist.

- Rob
.

**Comment by Lewis-Kang** [comment] 2016-02-15 03:39
I just gave it a try. This issue remains unsolved yet.

**Comment by capveg** [comment] 2016-02-15 18:47
Thanks Lewis for the feedback.

If you're still seeing the issue, can you run `make docker-debug` and send
us the output before you get to the prompt as well as the output of:

ls -l /proc/sys/fs/binfmt_misc/
from inside the docker shell?

Also your version of docker:
robs@sbs2:~$ docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.3.3
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.3.3
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64

Thanks,

- Rob
.

**Comment by sonoble** [comment] 2016-02-15 18:50
FYI here are the details of how those files get into the docker7/8 images:

docker/images/builder7/1.0$ grep i2c-devices.h Dockerfile
RUN cp /usr/include/linux/i2c-dev.h /usr/include/linux/i2c-devices.h && \
    cp /usr/include/linux/i2c-dev.h /usr/powerpc-linux-gnu/include/linux/i2c-devices.h

Can you confirm that they are there? We have not seen this issue in quite a while..

**Comment by Lewis-Kang** [comment] 2016-02-16 01:57
Rob, here is what I got. Thanks.

root@CicadaBuildServer:/home2/kang/OCP/OpenNetworkLinux# make docker-debug
Pulling opennetworklinux/builder7:1.0...
done.
[ ok ] Starting apt-cacher-ng: apt-cacher-ng.
Ready to build OpenNetworkLinux.
root@onlbuilder7:~# ls -l /proc/sys/fs/binfmt_misc/
total 0

kang@CicadaBuildServer:~$ docker version
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:29:38 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:29:38 UTC 2015
 OS/Arch:      linux/amd64

**Comment by Lewis-Kang** [comment] 2016-02-16 08:15
After applying Steven's changed files in https://github.com/opencomputeproject/OpenNetworkLinux/pull/39 , which have not merged back to master branch yet, this issue is gone. Thanks.

**Comment by sonoble** [comment] 2016-02-16 14:03
Hi Lewis,

That is good to hear :)

I need to talk to @jnealtowns about the change as I believe I bumped the docker image prematurely since the change is in the docker_shell.  We may just update the 1.0 image, which the make docker command will pull if it has changed.

**Comment by Dodain** [comment] 2016-02-16 15:57
Hi, 
@Lewis-Kang  Are you using debain 8? 

@sonoble   I am not having the directory /usr/powerpc-linux-gnu/include/linux/ , and  i did update the files as mentioned in #39 , 

Docker version is as follow.

root@Dodain:/# docker version
Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:16:19 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:16:19 2016
 OS/Arch:      linux/amd64

**Comment by sonoble** [comment] 2016-02-16 23:08
Hi Dodain.

I am not sure why we are having trouble with the i2c headers.  Please pull the latest version of the code, set the variable VERSION to 8 and run make docker.  We have updated the docker images and the way the system builds.

**Comment by Dodain** [comment] 2016-03-07 16:42
Hi 
Well sorry for the late update.After pulling the latest version of the code, the prob is solved and image is built successfully.Thanks.

**Comment by sonoble** [comment] 2016-03-07 19:09
No worries, we have been working hard to make sure that the builds go correctly.  Let us now if you have any other issues.
